base_url = "https://sernik.tech"
ring_name = "Sernik"
ring_description = "A webring of silly people - many inside Rexo's walls - who like cheesecake"
ring_owner = "Sophie L (Rexogamer)"
ring_owner_site = "https://rexogamer.github.io"

filepath_list = "./websites.json"   # Website list; should be a JSON file with 'name', 'url', etc
path_output = "./webring"           # Generated files will be saved in this folder.
path_assets = "./data/assets"       # All contents of the asset folder will be copied directly into the output directory
path_templates = "./data/templates" # The folder containing HTML templates to use, ie, anything with {{ tags }}

client_user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"
client_header = "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
audit_retries_delay = 100
audit_retries_max = 2

shuffle = false     # Randomizes website sequence when generating
verbose = false     # Enables verbose logging
skip_minify = true  # If your generated HTML have issues, or you want hand-editable output, try skip minification
skip_verify = false # Skips verification of the URLs in the list. Might be unwise!
dry_run = false     # Perform a dry run without writing any files. Can be used to check the site audit for example.
